// Writes src/styles/tokens.css (and a copy, public/tokens.css, for the standalone pages) and src/design/tokens.gen.ts
// from src/design/tokens.json, the design system's token file (dark theme first, light second). Every colour the app
// draws comes from here: the CSS holds one custom property per token (--bg, --surface, --steps-end…) for each theme,
// and the TS module the few values code needs outside CSS (the browser bar's colour). Run `npm run tokens` after
// editing tokens.json; tests/unit/tokens.test.ts checks the generated files match it.
import fs from "node:fs";
import { fileURLToPath } from "node:url";

const root = new URL("..", import.meta.url);
const read = () => JSON.parse(fs.readFileSync(new URL("src/design/tokens.json", root), "utf8"));

/** The generated CSS and TS for a token object, as strings. */
export function generate(t = read()) {
  const [first, second] = t.color.themes.map((th) => th.id);
  const colors = (theme) => t.color.tokens.map((c) => `  --${c.name}: ${typeof c.value === "string" ? c.value : (c.value[theme] ?? c.value[first])};`).join("\n");
  const plain = (fam) => (t[fam]?.tokens ?? []).map((x) => `  --${x.name}: ${x.value};`).join("\n");
  const fam = (name) => (name === "sans" ? "var(--font-sans)" : name);
  const styles = t.type.groups
    .flatMap((g) => g.styles.map((s) => `  --type-${s.name}: ${s.fontWeight} ${s.fontSize}/${s.lineHeight} ${fam(g.family)};`))
    .join("\n");
  const css = `/* Generated by scripts/build-tokens.mjs from src/design/tokens.json. Don't edit: change tokens.json and run
   npm run tokens. ${first[0].toUpperCase() + first.slice(1)} is the default theme; ${second} follows the system setting, or data-theme on <html>
   (Settings → Appearance). */
:root {
  color-scheme: ${first};
${colors(first)}
${plain("spacing")}
${plain("radius")}
${plain("size")}
  --font-sans: var(--font-nunito), ${t.type.families.sans};
${styles}
  --ease: cubic-bezier(0.2, 0.8, 0.2, 1);
  --press: 120ms;
  --sheet: 200ms;
  --ring-draw: 0.9s;
  --bar-grow: 0.6s;
}
@media (prefers-color-scheme: ${second}) {
  :root:not([data-theme="${first}"]) {
    color-scheme: ${second};
${colors(second).replace(/^/gm, "  ")}
  }
}
:root[data-theme="${second}"] {
  color-scheme: ${second};
${colors(second)}
}
`;
  const bg = t.color.tokens.find((c) => c.name === "bg").value;
  const ts = `// Generated by scripts/build-tokens.mjs from src/design/tokens.json. Don't edit: run npm run tokens.
/** The screen background in each theme, for the browser's bar (theme-color) and the Android status bar. */
export const BG = { ${first}: ${JSON.stringify(bg[first])}, ${second}: ${JSON.stringify(bg[second])} } as const;
`;
  return { css, ts };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const { css, ts } = generate();
  fs.writeFileSync(new URL("src/styles/tokens.css", root), css);
  fs.writeFileSync(new URL("src/design/tokens.gen.ts", root), ts);
  // The same file for the site's standalone pages (public/app-login.html, privacypolicy.html), which aren't built.
  fs.writeFileSync(new URL("public/tokens.css", root), css);
  console.log("Wrote src/styles/tokens.css, src/design/tokens.gen.ts and public/tokens.css");
}
