// Generated by scripts/build-tokens.mjs from src/design/tokens.json. Don't edit: run npm run tokens.
/** The screen background in each theme, for the browser's bar (theme-color) and the Android status bar. */
export const BG = { dark: "#0E0F11", light: "#F2F3F5" } as const;
